### PR TITLE
httpok_emit_logger

### PR DESCRIPTION
**Pull request by ParthKolekar**
-C Option specifies the stream onto which httpok will start to emit
messages which would trigger a Process Communication event. Useful for
logging what httpok is doing.

 Default: None

### CODE REVIEW

**Comment by mnaberez** [comment]
Does capture mode work with eventlisteners?  It's [not supposed to](http://supervisord.org/logging.html#capture-mode):

> The output of processes specified as “event listeners” (`[eventlistener:x]` sections) is not processed this way. Output from these processes cannot enter capture mode.

**Comment by ParthKolekar** [comment]
I could not figure out what that documentation was trying to say. 

So I tried it out. It works out as expected when the `stderr_capture_maxbytes` is set to a non-zero value. 

Tested on Supervisor 3.0a12. This might have been removed from newer versions. It is un-tested there.

**Comment by ParthKolekar** [comment]
http://supervisord.org/configuration.html#eventlistener-x-section-example
The eventlistener-example seems to suggest that it does.

**Comment by mnaberez** [comment]
> I could not figure out what that documentation was trying to say. 

[Configuring an Event Listener](http://supervisord.org/events.html#configuring-an-event-listener) is clearer:

> Supervisor does not respect “capture mode” output from event listener processes (ie. event listeners cannot be PROCESS_COMMUNICATIONS_EVENT event generators)

**Comment by mnaberez** [comment]
> http://supervisord.org/configuration.html#eventlistener-x-section-example
The eventlistener-example seems to suggest that it does. 

I think this is likely a copy-paste error.

**Comment by ParthKolekar** [comment]
I can confirm this working in 3.2.0 as well.

**Comment by mnaberez** [comment]
I've been thinking about this for a while and I have decided not to merge this, sorry.  I don't see this as being enough of a mainstream feature to be included in the Superlance package.  I also don't want to have to modify all the other eventlisteners in this package for parity with this change.  There's no reason why all changes/additions have to be included in Superlance itself anymore (there are now [many other plugins](http://supervisord.org/plugins.html).  Please run your own version of httpok if you need this change.  The license allows you to release that as a package also.

**Pull request closed without merging**
