### PR TITLE
Update process_state_email_monitor.py

### PR DESCRIPTION
**Pull request by ParthKolekar**
Indent using 4 spaces, not two.

### CODE REVIEW

**Comment by mnaberez** [comment]
Please refrain from style changes. PRs for bug fixes or new features are fine.

**Comment by ParthKolekar** [comment]
@mnaberez 

The line is indented with a total of 10 spaces. I am not doing a style change.

**Comment by mnaberez** [comment]
We'd be happy to review PRs that fix bugs or add features, but PRs that fix these sorts of mechanical issues in source code aren't really needed.  They just create merge conflicts with outstanding patches.  The whitespace isn't perfect but it's not worth changing if that's going to conflict with other patches.  The maintainers can always make these sorts of changes or run a tool to do them.  The things we really want patches for are bugs.

**Comment by ParthKolekar** [comment]
Cool.

**Pull request closed without merging**
