### PR TITLE
Updated fatalmailbatch.py

### PR DESCRIPTION
**Pull request by ParthKolekar**
Removed trailing whitespace

### CODE REVIEW

**Comment by mnaberez** [comment]
Please refrain from style changes (or whitespace). PRs for bug fixes or new features are fine.

**Comment by ParthKolekar** [comment]
There is an idle trailing whitespace in the file. That is not a style change.

**Comment by mnaberez** [comment]
Please see [this response](https://github.com/Supervisor/superlance/pull/86#issuecomment-231241803).

**Comment by ParthKolekar** [comment]
Cool.

**Pull request closed without merging**
